FROM node:18-alpine
ENV NODE_ENV=production

RUN mkdir /app

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --omit=dev

COPY . .
copy ../src ../src

CMD ["node", "main.mjs"]

EXPOSE 5000
